defaults:
  - _self_
  - data: mslr30k
  - logging_policy_ranker: linear
  - logging_policy_sampler: e_greedy
  - bias_tower: embedding
  - relevance_tower: linear

dataset_dir: "~/ltr_datasets"
# dataset_dir: "~/Documents/Uni/Project_AI/ltr_datasets"

experiment: default
random_state: 42

# Configure dataset pre-processing:
use_cross_validation: False # Use cross-validation splits
sample_queries: null # Optionally sample subset of queries from the dataset
features: all # Select query-document feature columns, e.g., 0-10.
relevance: original # [original, linear, deep]
relevance_noise: 0.0 # Add gaussian noise to synthetic relevance labels
relevance_quantization: False # Converts continuous relevance scores to integers

# Click simulation:
train_clicks: 1000_000
val_clicks: 500_000
test_clicks: 500_000
policy_strength: 1.0
policy_temperature: 0.0
bias_strength: 1.0
param_shift: 0.0

# Two-tower model:
use_propensity_weighting: False
freeze_bias_tower: False
single_param: False
param_idx: 0
save_test_datasets: False
load_test_datasets: False
test_dataset_name: "test_dataset_name.pkl"
test_click_dataset_name: "test_click_dataset.pkl"

# custom dataset generation
num_groups: 1
docs_per_group: 10
D: 100
s_group: 0.0
s_doc: 0.5
num_queries: 10
label_type: deep
use_baidu: False
baidu_subset: "train_Baidu_ULTRA_part1.npz"

hydra:
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - freeze_bias_tower
          - param_shift
          - param_idx
          - single_param
          - save_test_datasets
          - load_test_datasets
          - test_dataset_name
          - test_click_dataset_name
          - num_groups
          - D
          - s_group
          - label_type
          - policy_strength
          - random_state
          - use_baidu
  output_subdir: .
  run:
    dir: results
  sweep:
    dir: results/${experiment}
    subdir: ${hydra.job.override_dirname}
