defaults:
  - _self_
  - data: mslr30k
  - logging_policy_ranker: linear
  - logging_policy_sampler: e_greedy
  - bias_tower: embedding
  - relevance_tower: linear

dataset_dir: "~/ltr_datasets"
# dataset_dir: "~/Documents/Uni/Project_AI/ltr_datasets"

experiment: default
random_state: 42

# Configure dataset pre-processing:
use_cross_validation: False # Use cross-validation splits
sample_queries: null # Optionally sample subset of queries from the dataset
features: all # Select query-document feature columns, e.g., 0-10.
relevance: original # [original, linear, deep]
relevance_noise: 0.0 # Add gaussian noise to synthetic relevance labels
relevance_quantization: False # Converts continuous relevance scores to integers

# Click simulation:
train_clicks: 100_000
val_clicks: 50_000
test_clicks: 50_000
policy_strength: 1.0
policy_temperature: 0.0
bias_strength: 1.0
param_shift: 0.0

# Two-tower model:
use_propensity_weighting: False
freeze_bias_tower: False
single_param: False
param_idx: 0

hydra:
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - freeze_bias_tower
          - param_shift
          - param_idx
          - single_param
  output_subdir: .
  run:
    dir: results
  sweep:
    dir: results/${experiment}
    subdir: ${hydra.job.override_dirname}
