#!/bin/bash
#SBATCH --partition=rome
#SBATCH --job-name=Test-Run
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=00:10:00

#SBATCH --array=1-6
#SBATCH --output=slurm/slurm_array_testing_%A_%a.out

module purge
module load 2023
module load CUDA/12.4.0
source .venv/bin/activate

HPARAMS_FILE="scripts/hparams_varying_single_experiment_main.txt"

srun python main.py -m $(head -$SLURM_ARRAY_TASK_ID $HPARAMS_FILE | tail -1)
    