#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=Test-Run
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=02:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2  # You may not need Anaconda if UV is installed separately
module load CUDA/12.4.0
source .venv/bin/activate

python create_custom_dataset.py

python main.py -m \
  experiment=test_varying_deep \
  data=Custom_dataset \
  relevance=deep \
  logging_policy_ranker=deep \
  relevance_tower=deep \
  policy_strength=1 \
  policy_temperature=0 \
  random_state=2021 \
  $@


python varying.py -m \
  experiment=test_varyding_deep \
  data=Custom_dataset \
  relevance=deep \
  logging_policy_ranker=deep \
  relevance_tower=deep \
  policy_strength=1 \
  policy_temperature=0 \
  random_state=2021 \
  freeze_bias_tower=True \
  $@
