# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

dataset_dir: "/ivi/ilps/projects/ltr_datasets"

hydra:
  launcher:
    mem_gb: 32
    cpus_per_task: 16
    array_parallelism: 8
    timeout_min: 3600
    partition: gpu
    gres: gpu:1
